version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    groups:
      maintenance:
        update-types:
          - "all"
    reviewers:
      - "vanbuiten"
    assignees:
      - "vanbuiten"
    labels:
      - "maintenance"
    commit-message:
      prefix: "chore"
      include: "scope"
      message: "Maintenance: Update all dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Amsterdam"
    groups:
      security:
        update-types:
          - "security"
    reviewers:
      - "vanbuiten"
    assignees:
      - "vanbuiten"
    labels:
      - "security"
    commit-message:
      prefix: "fix"
      include: "scope"
      message: "Security: Update dependencies for security vulnerabilities"