version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "daily"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    groups:
      maintenance:
        update-types:
          - "major"
          - "minor"
          - "patch"
    reviewers:
      - "vanbuiten"
    assignees:
      - "vanbuiten"
    labels:
      - "maintenance"
    commit-message:
      prefix: "Maintenance"
      include: "scope"
