version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:15"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    assignees:
      - "vanbuiten"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Amsterdam"
