version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      possible-breaking-changes:
        update-types:
          - "major"
    reviewers:
      - "vanbuiten"
    assignees:
      - "vanbuiten"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Amsterdam"

  - package-ecosystem: "pip"
    directory: "/"
    groups:
      maintenance:
        - "minor"
        - "patch"
    reviewers:
      - "vanbuiten"
    assignees:
      - "vanbuiten"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "Europe/Amsterdam"
