version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Amsterdam"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Amsterdam"
    groups:
      maintenance:
        applies-to: "version-updates"
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Maintenance"
