version: '3.4'

services:
  app:
    image: vanbuiten/sandbox
    build:
      context: .
      target: app
    ports:
      - "8240:8000"
    volumes:
      - .:/app

  docs:
    image: vanbuiten/sandbox
    build:
      context: .
      target: docs
    ports:
      - "8241:8000"
    volumes:
      - .:/app
