version: '3.4'

services:
  app:
    build:
      context: backend/.
      target: app
    depends_on:
      - database
    ports:
      - "8240:8000"
    volumes:
      - ./backend/app:/app
    env_file: .env
    command:
      - uvicorn
      - app.api:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  database:
    image: postgres:16.1
    ports:
      - "5409:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  docs:
    build:
      context: backend/.
      target: docs
    ports:
      - "8241:8000"
    volumes:
      - .:/app/backend/app
    env_file: .env

volumes:
  database-data:
