site_name: Dune
site_description: ...

theme:
  name: "material"
  language: "en"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.footer

extra:
  generator: false

plugins:
  search:
    lang: "en"
  literate-nav:
    nav_file: "summary.md"
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          show_docstring_examples: true
          annotations_path: brief
