name: Build and push the Signalen API when a new release is published

on:
  release:
    types: [ published ]

jobs:
  build_and_push:
    name: Build an Docker image for the release and push it to the DockerHub registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Release tag
        run: echo "${{ github.event.release.tag_name }}"

      - name: Build the Docker image release
        run: docker build -t davidvanbuiten/sandbox:${{ github.event.release.tag_name }} .

      - name: Push the tagged image to Docker
        run: docker push davidvanbuiten/sandbox:${{ github.event.release.tag_name }}
