name: Run linting, type checking and unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ruff
        run: docker-compose -f docker-compose.ci.yml run ci poetry run ruff check .

  mypy:
    name: Run type checking
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: mypy
        run: docker-compose -f docker-compose.ci.yml run ci bash -c "mypy signals | mypy-baseline filter"

  pytest:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs:
      - Ruff
      - MyPy

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: pytest
        run: docker-compose -f docker-compose.ci.yml run ci pytest .
