name: Create Branch

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
