name: Build and deploy docs

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Install dependencies
      - name: Install dependencies
        run: poetry install --with docs

      - name: Build documentation
        run: poetry run mkdocs build --clean --verbose

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
