name: pr-slack-notification

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - ready_for_review
      - review_requested
      - closed
  issue_comment:
    types:
      - created
  pull_request_review:
    types:
      - submitted

permissions: read-all

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    name: Sends a message to Slack
    if: github.repository == 'vanbuiten/sandbox'
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"

#      - name: Post PR summary message to slack
#        id: message
#        uses: slackapi/slack-github-action@v2.0.0
#        with:
#          method: chat.postMessage
#          token: ${{ secrets.MY_SLACK_BOT_TOKEN }}
#          payload: |
#            channel: ${{ secrets.MY_SLACK_CHANNEL_ID }}
#            text: "A PR has been created in repository ${{ github.repository }}: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
#
#      - name: Create file with slack message timestamp
#        run: |
#          echo "${{ steps.message.outputs.ts }}" > slack-message-timestamp.txt
#
#      - name: Cache slack message timestamp
#        uses: actions/cache@v4.2.3
#        with:
#          path: slack-message-timestamp.txt
#          key: slack-message-timestamp-${{ github.event.pull_request.html_url }}-${{ steps.message.outputs.ts }}
