name: Static analysis

on: [ pull_request ]

jobs:
  Ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build containers
        run: docker buildx bake --file compose.yaml

      - name: Run ruff formatter
        run: docker compose run --rm linting poetry run ruff check .

      - name: Run ruff linting
        run: docker compose run --rm linting poetry run ruff format --diff .

  MyPy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build containers
        run: docker buildx bake --file compose.yaml

      - name: Run MyPy
        run: docker compose run --rm linting poetry run mypy .
